### ISSUE TITLE
TS Error: Property 'attribs' does not exist on type 'DOMNode'.

### ISSUE THREAD

**Issue by bicstone** [remarkablemark/html-react-parser#199]
## Expected Behavior
When upgrade from version 0.14.3 to 1.0, TypeScript type errors occurs.

```
error TS2339: Property 'attribs' does not exist on type 'DOMNode'.
error TS2339: Property 'name' does not exist on type 'DOMNode'.
error TS2339: Property 'children' does not exist on type 'DOMNode'.
...etc
```

## Actual Behavior
No error occurs.

## Steps to Reproduce
Upgrade from version 0.14.3 to 1.0.

## Reproducible Demo
0.14.3: https://codesandbox.io/s/mutable-surf-7r84v?file=/src/App.tsx
1.0: https://codesandbox.io/s/async-wildflower-p1wxl?file=/src/App.tsx

MEMO: https://github.com/remarkablemark/html-react-parser/commit/5568ed72fb2c31c1924eac114f38d6294c3ba342#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8

**Comment by remarkablemark** [comment]
Thanks for opening this issue!

You'll need to do an `instanceof` check of domhandler's `Element`:

```tsx
import { Element } from 'domhandler';

const options: HTMLReactParserOptions = {
  replace: (domNode) => {
    if (
      domNode instanceof Element &&
      domNode.attribs &&
      domNode.name === 'main'
    ) {
      const props = attributesToProps(domNode.attribs);
      return <div {...props} />;
    }
  },
};
```

See https://codesandbox.io/s/html-react-parser-199-ehdss

I think this would be a good opportunity to consider exporting `Element` from the main TS definition file and updating the `README.md` about this gotcha during migration to `1.0.0`.

**Comment by bicstone** [comment]
Now I understand.
Thank you for your explanation!

**Comment by bicstone** [comment]
@remarkablemark  Can I ask you just one more question?
Is this a problem with the type defined in the `domhandler` ?

## Expected Behavior
No error occurs.

## Actual Behavior
When upgrade from version 0.14.3 to 1.0, TypeScript type errors occurs.

```
error TS2345: Argument of type 'Node[]' is not assignable to parameter of type 'DOMNode[]'.
  Type 'Node' is not assignable to type 'DOMNode'.
    Type 'Node' is missing the following properties from type 'Text': data, nodeValue
```

## Steps to Reproduce
Upgrade from version 0.14.3 to 1.0.

## Reproducible Demo
0.14.3: https://codesandbox.io/s/html-react-parser-199-forked-pqzg5?file=/src/App.tsx
1.0: https://codesandbox.io/s/html-react-parser-199-forked-k1kcy?file=/src/App.tsx

**Comment by kevinpfox** [comment]
If you ended up here and tried the recommended solution and it still didn't work and you aren't interested in processing "Text" nodes and only care about processing "Tag" nodes, you can try the following...

```
import { isTag } from 'domhandler/lib/node';

replace: (domNode) => {
  if (isTag(domNode)) {
    const { attribs, children, name } = domNode;
  }
```

I don't know why the recommended solution did not work in our project. It looks logical. For our project `domNode instanceof Element` was always evaluating as `false` and execution refused to drop into the protected block.

**Comment by kevinpfox** [comment]
@remarkablemark, thank you for making your great tool available! Would be great if  `isTag` and `Element` from `domhandler` library were exposed via `html-react-parser`, so `domhandler` doesn't need to be added as a project dependency. At some point I wonder if `html-react-parser`'s `domhandler` and our `domhandler` versions will go far enough out of sync to introduce a breaking change in the future.

**Comment by remarkablemark** [comment]
@kevinpfox I'm open to exporting `isTag` (and maybe `Element`) from `domhandler` if a lot of people are experiencing pain with the current approach.

I'm open to a PR but I do want to make sure including this won't add to the bundle size too much.

We can continue discussion in #252 if it's similar.

**Comment by kevinpfox** [comment]
Thanks for mentioning other thread. I tried the following approach and it fixed the same problem without needing to import an additional project dependency. https://gist.github.com/natterstefan/3bc712eca6ff88781d687b7240a78cc1   I'm also working on a Next.js project.

**Comment by remarkablemark** [comment]
Nice! If this is helpful, would you be interested in opening a PR to document that approach in the `README.md`?

**Comment by peckyboy** [comment]
> Thanks for opening this issue!
> 
> You'll need to do an `instanceof` check of domhandler's `Element`:
> 
> ```tsx
> import { Element } from 'domhandler/lib/node';
> 
> const options: HTMLReactParserOptions = {
>   replace: (domNode) => {
>     if (
>       domNode instanceof Element &&
>       domNode.attribs &&
>       domNode.name === 'main'
>     ) {
>       const props = attributesToProps(domNode.attribs);
>       return <div {...props} />;
>     }
>   },
> };
> ```
> 
> See https://codesandbox.io/s/html-react-parser-199-ehdss
> 
> Let me know if you think exporting `Element` from `html-react-parser` and/or updating the `README.md` would help.

Why is this so though? I think exporting `Element` from `html-react-parser` and/or updating the `README.md` would help greatly.
Thank you.

**Comment by remarkablemark** [comment]
#296 released in [1.4.0](https://github.com/remarkablemark/html-react-parser/pull/306)

**Comment by dbehmoaras** [comment]
> Thanks for opening this issue!
> 
> You'll need to do an `instanceof` check of domhandler's `Element`:
> 
> ```tsx
> import { Element } from 'domhandler/lib/node';
> 
> const options: HTMLReactParserOptions = {
>   replace: (domNode) => {
>     if (
>       domNode instanceof Element &&
>       domNode.attribs &&
>       domNode.name === 'main'
>     ) {
>       const props = attributesToProps(domNode.attribs);
>       return <div {...props} />;
>     }
>   },
> };
> ```
> 
> See https://codesandbox.io/s/html-react-parser-199-ehdss
> 
> Let me know if you think exporting `Element` from `html-react-parser` and/or updating the `README.md` would help.

I tried this solution, but it does not work. The instanceof check returns false on every run. Unfortunately due to factors out of my control, we are unable to update to 1.4 (at least not yet). Do you have any other ideas? I would greatly appreciate your thoughts. Thanks!
