### ISSUE TITLE
domNode instanceof Element is suddenly false?

### ISSUE THREAD

**Issue by Jahrhause** [remarkablemark/html-react-parser#633]
## Expected Behavior

domNode instanceof Element should be true

## Actual Behavior

domNode instanceof Element is false

## Steps to Reproduce
After upgrading from version 1.4 to 3.0 domNode instanceof Element is suddenly returning false

## Reproducible Demo
```
import parse, { HTMLReactParserOptions, domToReact, Element, DOMNode } from 'html-react-parser';
import React, { FC } from 'react';

const Textblock: FC = () => {
  const htmlFromCMS = '<h1>Weird</h1><p>dsdsdsdsdsd</p>';

  const options: HTMLReactParserOptions = {
    trim: true,
    replace: (domNode) => {
      console.log(domNode instanceof Element);
      console.log('/******************************************************************/');
      if (domNode instanceof Element && domNode.attribs && domNode.type === 'tag') {
        switch (domNode.name) {
          case 'h1':
            return (
              <h1 className="sydb-textblock__heading sydb-textblock__heading--h1">
                {domToReact(domNode.children, options)}
              </h1>
            );
          case 'h2':
            return (
              <h2 className="sydb-textblock__heading sydb-textblock__heading--h2">
                {domToReact(domNode.children, options)}
              </h2>
            );
          case 'p':
            return (
              <p className="test">
                {domToReact(domNode.children, options)}
              </p>
            );          
          
        }
      }
    },
  };
    return (
      <article>
        {parse(htmlFromCMS, options)}
      </article>
    );
};

export default Textblock;
```

What could have happend?

## Environment

- Version: 3.0.1
- Platform: Next.js
- Browser: Chrome

**Comment by remarkablemark** [comment]
It should still work as expected. See [CodeSandbox](https://codesandbox.io/s/html-react-parser-633-nd6w4d?file=/src/index.js).

Try reinstalling your packages:

```sh
rm -rf node_modules
npm i
```

**Comment by jlegreid** [comment]
@Jahrhause @remarkablemark I am also having this issue, I have tried reinstalling my packages and it didn't seem to help. For now I have just replaced my `domNode instanceof Element` checks with `domNode.type === 'tag'` and that achieves the same result for my purposes at this time.

**Comment by remarkablemark** [comment]
Thanks for the heads up @jlegreid and sharing your workaround. I'll keep an eye out if more users are experiencing this.

**Comment by tremby** [comment]
I'm seeing the same thing.

**Comment by Jahrhause** [comment]
Just tried to downgrade to version 2.0.0 and now everything is back to the way it should be, so must be something in version 3.

For v.3 I used this workaround as of now:

```
const options: HTMLReactParserOptions = {
    trim: true,
    replace: (domNode) => {
      let element = domNode as Element;

      if (element.attribs && element.type === 'tag') {
        switch (element.name) {
          case 'h1':
            return (
              <h1 className="sydb-textblock__heading sydb-textblock__heading--h1">
                {domToReact(element.children, options)}
              </h1>
            );
          case 'h2':
            return (
              <h2 className="sydb-textblock__heading sydb-textblock__heading--h2">
                {domToReact(element.children, options)}
              </h2>
            );
          case 'p':
            return (
              <p className="test">
                {domToReact(element.children, options)}
              </p>
            );          
        }
      }
    },
  };
```
This way I still get the typings I need.

**Comment by remarkablemark** [comment]
Thanks for the updates everyone. Could I ask someone to try regenerating their lockfile as well as nuking node_modules?

```sh
rm -rf node_modules package-lock.json
npm i
```

Let me know if the error still persists if you try that.

**Comment by tremby** [comment]
@Jahrhause 
> For v.3 I used this workaround as of now:
...
> This way I still get the typings I need.

A bit better, imo, is to use a [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates):

Define a function like

```ts
function domNodeIsElement(domNode: DOMNode): domNode is Element {
  return domNode.type === "tag";
}
```

Then, as for usage, as soon as you've done

```ts
 if (!domNodeIsElement(domNode)) return;
```

any code after that knows that domNode is an Element.

**Comment by tremby** [comment]
@remarkablemark I would but I've just set off travelling for a week. Hopefully someone else can test that in the mean time.

**Comment by remarkablemark** [comment]
Sounds good @tremby

**Comment by TheRarita** [comment]
Not sure if this is related, but I am getting 
```
Property 'attribs' does not exist on type 'DOMNode & Element'.  
Property 'attribs' does not exist on type 'Comment & Element'.ts(2339)
```

https://codesandbox.io/s/kk0ovr?file=/src/App.tsx:252-259

**Comment by remarkablemark** [comment]
@TheRarita I think your CodeSandbox link is incorrect?

**Comment by TheRarita** [comment]
@remarkablemark Sorry, and double sorry. I corrected the link and also realized where my mistake was. I did not realize that `Element` should be imported from this library and it is not the general base [Element](https://developer.mozilla.org/en-US/docs/web/api/element). The name is a bit confusing but also, I did not read it properly since it is clearly imported in the snipped I linked.

**Comment by remarkablemark** [comment]
No worries @TheRarita. Thanks for the update.

**Comment by charkour** [comment]
Hey @remarkablemark, after upgrading to v2 to v3, I had the same error. Removing and clearing the `node_modules` fixed the issue. Had to do the same to the CI/CD pipeline.

Any idea why this would seemingly break when `node_modules` are cached during the version update?

**Comment by charkour** [comment]
Okay, an update on the situation. After removing and reinstalling `node_modules`, `domNode instanceof Element` correctly returns a boolean value when the page is SSR'd, but not CSR'd (on Next.js). So any sort of page navigation that runs the parser will always return `false` for the `domeNode instanceof Element` check.

**Comment by remarkablemark** [comment]
@charkour Just confirming, `domNode instanceof Element` check is working on the server-side, but not working on the client-side?

**Comment by charkour** [comment]
Hey, thanks for the quick response. I was initially a little confused and reported the wrong thing. 

In v3, the script tags will execute when the page is rendered on the server, but not when rendered on the client. 

In v2, script tags are executed both on the server and client. 

In both cases the `domNode instanceof Element` check is being used in the replace method. 

If I have time at work this week, I could make a minimal repro demo if that is helpful.

**Comment by remarkablemark** [comment]
@charkour A reproducible demo would definitely be helpful!

**Comment by JiriLojda** [comment]
@remarkablemark Hi, I encountered the same issue so I created a simple reproduction. It was originally created with `npx create-react-app --template=typescript`.  ([CodeSandbox](https://codesandbox.io/p/github/JiriLojda/html-react-parser-issue-repro/csb-36k02q/draft/trusting-blackburn?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A18%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A10%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cla72ik9k0006l1cxfw384ew6%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cla72j4w300bl356lznuog3uv%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cla72j2eo0090356li2ut6gnj%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) | [GitHub](https://github.com/JiriLojda/html-react-parser-issue-repro)) I hope it is helpful.

**Comment by remarkablemark** [comment]
@JiriLojda Thanks for creating the reproducible example. I can confirm that your [CodeSandbox](https://codesandbox.io/p/github/JiriLojda/html-react-parser-issue-repro/csb-36k02q/draft/trusting-blackburn?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A18%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A10%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cla72ik9k0006l1cxfw384ew6%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cla72j4w300bl356lznuog3uv%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cla72j2eo0090356li2ut6gnj%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) isn't working correctly, but when I forked and created my own [CodeSandbox](https://codesandbox.io/s/html-react-parser-633-t7q605?file=/src/App.tsx), it seems to be working as expected.

**Comment by jt3k** [comment]
faced with same problem.
I am using version 3.0.4 and the problem is the same as in version 1.4.5.
also my environment: node 8.16, typescript 3.9.9, webpack 4.17

inside the repeater, I am met by a domNode instance of the wrong Element that can be imported from
```js
import parse, { Element } from 'html-react-parser';
```

i created a check inside the replace function,
```js
    console log({
      assert1: domNode.constructor === Element,
      assert2: domNode instanceof Element,
      Element1: Element
      Element2: domNode.constructor
    });
```
when inspecting in devTools, I found that the links lead to two identical files with the [same content](https://www.diffchecker.com/nEvauWtz):

```
webpack:///node_modules/html-dom-parser/node_modules/domhandler/lib/node.js
webpack:///node_modules/html-react-parser/node_modules/domhandler/lib/node.js
```
<img width="548" alt="image" src="https://user-images.githubusercontent.com/1261240/203845968-aaf294ca-9663-47f9-8f63-0cfeaedfd765.png">


This seems to be why typescript shows an error and the script doesn't work on the client.
before, I just wrote "any" in those places where the typescript swears. but I would like to solve the problem more gracefully. Thanks!

**Comment by remarkablemark** [comment]
Thanks for sharing your findings @jt3k. In your case, I think performing a type assertion makes sense since `Element` are 2 distinct objects.

**Comment by haleetwilio** [comment]
running into same issue. using latest version of html-react-parser and using react 18.

**Comment by haleetwilio** [comment]
@charkour thank you for quick response. This definitely helps! :) is there a plan to fix the bug in coming future? or is the use case too small (or the root cause is not clear yet) that we just have to use the workaround method? totally understand if the answer is latter - just want to inform our team . 

aside from this, thank you for the work on this package. it's awesome :) helping us a ton

**Comment by charkour** [comment]
@remarkablemark had previously asked for a reproduction and I couldn't consistently reproduce it, but it seemed to happen when npm was caching TS types while switching between versions of this package.

**Comment by remarkablemark** [comment]
@haleetwilio as mentioned above, this bug can't be consistently reproducible, so there is no plan to fix this. The current workaround suffices and it's documented in the README.md

**Comment by sauron918** [comment]
Running into same issue in v4.0.0, no switching between versions were previously done.

**Comment by remarkablemark** [comment]
@sauron918 can you try deleting and reinstalling `node_modules`?

**Comment by bricejar** [comment]
Hi, just used this library for the first time and the same problem appeared randomly.

**Comment by remarkablemark** [comment]
@bricejar what version are you using? Can you use the workaround provided by one of the previous commenters?

**Comment by bricejar** [comment]
@remarkablemark I am using 4.2.5 and yes I am using a workaround for now. Thank you !

**Comment by jt3k** [comment]
Maybe there is a way to solve the problem without resorting to a workaround?  let's fix it?  because it’s clearly obvious what the reason is, instances are created by different Element classes, so inside the replacer function typescript does not recognize it as a correct Element instance

**Comment by Valithor** [comment]
Installed the package today, got the same problem right away

**Comment by terrymun** [comment]
Ran into the same issue when upgrading fro v5.2.17 to v6. It seems that the solution proposed in https://github.com/remarkablemark/html-react-parser/issues/633#issuecomment-1485590066 works. I initially tried doing a fresh install of `node_modules` but that didn't fix the issue.

**Comment by remarkablemark** [comment]
@terrymun can you check your versions?

```sh
npm ls domhandler # should be 6.0.1
```

```sh
npm ls htmlparser2 # should be 12.0.0
```

**Comment by terrymun** [comment]
@remarkablemark Can confirm that `domhandler` is at 6.0.1 and `htmlparser2` is at 12.0.0:

```text
$ pnpm why domhandler
domhandler@6.0.1
├─┬ dom-serializer@3.0.0
│ └─┬ domutils@4.0.2
│   └─┬ htmlparser2@12.0.0
│     └─┬ html-dom-parser@7.0.0
│       └─┬ html-react-parser@6.0.0
│         └── [REDACTED] (dependencies)
├── domutils@4.0.2 [deduped]
├── html-dom-parser@7.0.0 [deduped]
├── html-react-parser@6.0.0 [deduped]
└── htmlparser2@12.0.0 [deduped]

$ pnpm why htmlparser2
htmlparser2@12.0.0
└─┬ html-dom-parser@7.0.0
  └─┬ html-react-parser@6.0.0
    └── [REDACTED] (dependencies)
```

**Comment by remarkablemark** [comment]
Thanks @terrymun. Strange that the error occurred, I'll keep an eye out if there are more reports.

**Comment by ds-ms2soft** [comment]
I'm also seeing this after upgrading to 6.0.1 (from 1.4.14). I have multiple versions of domhandler. Wiping my node_modules and package-lock.json did not fix it.
